### ISSUE TITLE
Missing Schema: invalid url '1'

### ISSUE THREAD

**Issue by David-Eilers** [beaston02/MFCRecorder#15]
getting the following error using the new web interface.
`
requests.exceptions.MissingSchema: Invalid URL '1': No schema supplied. Perhaps you meant http://1? 
`
this is probably something simple but havent been able to spot the problem yet.

<details><summary>Click to expand full stacktrace</summary>

```python
C:\Users\David\AppData\Local\Programs\Python\Python35\python.exe "C:/Users/David/Documents/Programeren/Eigen Projecten/MFCRecorder/MFCRecorder.py"
____________________Connection Status____________________
Connecting to MyFreeCams chat server xchat123...
 * Running on http://0.0.0.0:8778/ (Press CTRL+C to quit)
Login handshake completed. Logged in as 'Guest09340' with sessionId 299644239
starting capture of model: RaeRiley  condition: 
starting capture of model: Anastasiaxx89  condition: 
starting capture of model: JustBea_7Year  condition: 
Traceback (most recent call last):
  File "C:/Users/David/Documents/Programeren/Eigen Projecten/MFCRecorder/MFCRecorder.py", line 247, in <module>
    getOnlineModels()
  File "C:/Users/David/Documents/Programeren/Eigen Projecten/MFCRecorder/MFCRecorder.py", line 144, in getOnlineModels
    recordModel(model, now)
  File "C:/Users/David/Documents/Programeren/Eigen Projecten/MFCRecorder/MFCRecorder.py", line 100, in recordModel
    response = requests.get(model['avatar'])
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\David\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '1': No schema supplied. Perhaps you meant http://1?
```
</details>

**Comment by beaston02** [comment]
Did you update the getModels.py file also? The URL which is throwing the error is generated in that file.

**Comment by David-Eilers** [comment]
I pulled changes via git so i think getmodels.py should also be updated, but i will verify it to be sure

**Comment by David-Eilers** [comment]
I have redownloaded the changed files and replaced my current files and now everything works again.

It was indeed the getmodels.py. it seems i accidentally deleted or misplaced that file.

I wanna add that when you visit `http://localhost:8778` instead of `http://localhost:8778/MFC` you get an `500 Internal Server Error` and when you visit `http://localhost:8778/mfc` you get an `404 Not Found ` error.

**Comment by beaston02** [comment]
Thanks

I added an exception for that error (it doesn't really have any effect on the script working, it just wont load that users avatar in the browser if it doesn't succeed). 

There is also a new module which must be installed so run `pip3 install colorama` This allows for colored logging in the terminal window (new recordings are logged green, completed recordings are logged red...) 

(your latest post just came through at this point in my response)

Im glad you got it working! 

Yes, Im aware of both of those conditions. I will probably create a redirect for either of those.

**Comment by David-Eilers** [comment]
Thank you for taking the time to help me and for being active on the repo.
Those url quirks are real small but will certainly improve usability.

I will check out the new changes shortly
