### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by forsomefun** [beaston02/MFCRecorder#32]
I was trying to use this program with a fresh install 
could not get it to find the wanted list.

I can show the errors Later but I belive the error is with the new mfcrecord.py
I was having a bunch of errors until I went back to one of my backups, and the program started to work again.

**Comment by forsomefun** [comment]
1. Going to try to change the path to the .txt file
2. Trying to move the wanted.json file to my MFC folder, changed wanted folder path to this location
3. Try add.py
4. Didn't try the web interface because I don't use it.


All didn't work

**Comment by beaston02** [comment]
Sorry for not quoting things, I'm replying from my phone. 

Your first error reports a problem with your config file. It seems like most commonly people don't have it named correctly. It should be "config.conf" and in the MFCRecorder directory. 

Your second error is most likely caused by your wanted file not being in the json format. If you move/delete it, and make sure your config.conf file is named correctly, and doesn't have any errors in it, it should work fine.

**Comment by forsomefun** [comment]
Does the folder need to be named 
MFCRecorder
I have mine as 
MFC

**Comment by beaston02** [comment]
MFC is fine.

**Comment by sKanoodle** [comment]
@forsomefun With the rework of the script I did, I introduced a new wanted format. There is a sample file called wanted.sample.json. In there, there is a exemplary entry for a model. There are more options now than only "record that model". They are all commented there.

To convert your old wanted.txt (which only contains numbers) there is a script called convert.py. This script reads your config.conf to know where the new wanted list is (wanted.json per default). wanted.json does not have to exist, it will be created when it's not there. The script then needs your old wanted.txt as argument and will add all the models from there to the new list.

so navigate to the MFC folder, and then execute 
convert.py wanted.txt

It should report a progress when it adds models, that's how you will see if it works. After it finished you should see the entries in the wanted.json with all the new options.

**Comment by forsomefun** [comment]
1. CD into MFC folder 
2. Ran code you gave.
3. In another attempt Added python3 or python3.6 to the code you gave 

Errors
convert.py wanted.txt
Command not found 


  File "convert.py", line 8, in <module>         
    conf = classes.config.Config(os.path.join(sys
.path[0], 'config.conf'))                        
  File "/root/MFCRecorder/classes/config.py", lin
e 79, in __init__                                
    self.refresh()                               
  File "/root/MFCRecorder/classes/config.py", lin
e 98, in refresh                                 
    self._filter = Filter(self._parser, self.sett
ings)                                            
  File "/root/MFCRecorder/classes/config.py", lin
e 60, in __init__                                
    self.wanted = Wanted(settings)               
  File "/root/MFCRecorder/classes/config.py", lin
e 184, in __init__                               
    self._load()                                 
  File "/root/MFCRecorder/classes/config.py", lin
    self._load()                                 
  File "/root/MFCRecorder/classes/config.py", lin
e 189, in _load                                  
    self.dict = {int(uid): data for uid, data in 
json.load(file).items()}                         
  File "/usr/lib/python3.6/json/__init__.py", lin
e 299, in load                                   
    parse_constant=parse_constant, object_pairs_h
ook=object_pairs_hook, **kw)                     
  File "/usr/lib/python3.6/json/__init__.py", lin
e 354, in loads                                  
    return _default_decoder.decode(s)            
  File "/usr/lib/python3.6/json/decoder.py", line
 342, in decode                                  
    raise JSONDecodeError("Extra data", s, end)  
json.decoder.JSONDecodeError: Extra data: line 2 
column 1 (char 7)

**Comment by sKanoodle** [comment]
looks like you already have stuff in your wanted.json. make sure the file does not already exist. I could imagine you copied your wanted.txt and just renamed it to wanted.json? that will not work.

**Comment by forsomefun** [comment]
I got it working somehow

I notice this error on start 
/root/scripts/mfcr.sh: line 1: !/bin/bash: No such file or directory                                                                            
another run 2017-11-15 08:08:49.645111                                                                                                          
Exception in thread Thread-9:                                                                                                                   
Traceback (most recent call last):                                                                                                              
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                         
    self.run()                                                                                                                                  
  File "/usr/lib/python3.6/threading.py", line 864, in run                                                                                      
    self._target(*self._args, **self._kwargs)                                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 841, in run                                                                  
    run_simple(host, port, self, **options)                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 739, in run_simple                                                    
    inner()                                                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 699, in inner                                                         
    fd=fd)                                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 587, in make_server                                                   
    passthrough_errors, ssl_context, fd=fd)                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 528, in __init__                                                      
    self.socket = ssl_context.wrap_socket(sock, server_side=True)                                                                               
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 450, in wrap_socket                                                   
    ssl_version=self._protocol, **kwargs)                                                                                                       
  File "/usr/lib/python3.6/ssl.py", line 1149, in wrap_socket                                                                                   
    ciphers=ciphers)                                                                                                                            
  File "/usr/lib/python3.6/ssl.py", line 747, in __init__                                                                                       
    self._context.load_cert_chain(certfile, keyfile)                                                                                            
FileNotFoundError: [Errno 2] No such file or directory

I think the program crash yesterday as well. Will try to update mfcauto if possible. But this came up again even after restarting the computer

**Comment by forsomefun** [comment]
The program still runs. Just that error is how it starts up. Not sure if it is important in a way

**Comment by forsomefun** [comment]
The program stopped with this error 
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
[2017-11-15 19:11:11,070] Login handshake completed. Logged in as 'Guest89521' with sessionId 760315897                                         
1325 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.              
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
finished run                                                                                                                                    
another run 2017-11-15 19:10:29.724658                                                                                                          
[2017-11-15 19:10:30,414] Connecting to MyFreeCams chat server xchat29...                                                                       
[2017-11-15 19:10:30,978] Login handshake completed. Logged in as 'Guest85246' with sessionId 760309819                                         
1318 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:10:49.651540                                                                                                          
[2017-11-15 19:10:50,357] Connecting to MyFreeCams chat server xchat70...                                                                       
[2017-11-15 19:10:50,781] Login handshake completed. Logged in as 'Guest62441' with sessionId 760308561                                         
1318 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:09.725476                                                                                                          
[2017-11-15 19:11:10,420] Connecting to MyFreeCams chat server xchat106...                                                                      
[2017-11-15 19:11:11,070] Login handshake completed. Logged in as 'Guest89521' with sessionId 760315897                                         
1325 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:10:49.651540                                                                                                          
[2017-11-15 19:10:50,357] Connecting to MyFreeCams chat server xchat70...                                                                       
[2017-11-15 19:10:50,781] Login handshake completed. Logged in as 'Guest62441' with sessionId 760308561                                         
1318 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:09.725476                                                                                                          
[2017-11-15 19:11:10,420] Connecting to MyFreeCams chat server xchat106...                                                                      
[2017-11-15 19:11:11,070] Login handshake completed. Logged in as 'Guest89521' with sessionId 760315897                                         
1325 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
[2017-11-15 19:11:11,070] Login handshake completed. Logged in as 'Guest89521' with sessionId 760315897                                         
1325 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
another run 2017-11-15 19:11:29.660444                                                                                                          
[2017-11-15 19:11:30,364] Connecting to MyFreeCams chat server xchat66...                                                                       
[2017-11-15 19:11:30,884] Login handshake completed. Logged in as 'Guest40309' with sessionId 760311063                                         
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:12:09.666556                                                                                                          
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
1322 models online                                                                                                                              
finished run                                                                                                                                    
another run 2017-11-15 19:11:49.696274                                                                                                          
[2017-11-15 19:11:50,395] Connecting to MyFreeCams chat server xchat25...                                                                       
[2017-11-15 19:11:50,903] Login handshake completed. Logged in as 'Guest01516' with sessionId 760314901                                         
1329 models online                                                                                                                              
finished run                                                                                                                                    
[2017-11-15 19:12:10,354] Connecting to MyFreeCams chat server xchat30...                                                                       
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selecte
d_server), 8100)                                                                                                                                
  File "/usr/lib/python3.6/asyncio/base_events.py", line 733, in create_connection                                                              
    infos = f1.result()                                                                                                                         
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                                                       
    result = self.fn(*self.args, **self.kwargs)                                                                                                 
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo                                                                                 
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                     
socket.gaierror: [Errno -3] Temporary failure in name resolution                                                                                
Error in sys.excepthook:                                                                                                                        
Traceback (most recent call last):                                                                                                              
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook                                                    
    from apport.fileutils import likely_packaged, get_recent_crashes                                                                            
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>                                                                 
    from apport.report import Report                                                                                                            
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>                                                                  
    import apport.fileutils                                                                                                                     
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>                                                               
    from apport.packaging_impl import impl as packaging                                                                                         
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>                                                          
    import apt                                                                                                                                  
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>                                                                   
    import apt_pkg                                                                                                                              
ModuleNotFoundError: No module named 'apt_pkg'                                                                                                  
                                                                                                                                                
Original exception was:                                                                                                                         
Traceback (most recent call last):                                                                                                              
  File "/root/MFC/MFCRecorder.py", line 30, in <module>                                                                                         
    for uid, model in classes.models.get_online_models().items():                                                                               
  File "/root/MFC/classes/models.py", line 32, in get_online_models                                                                             
    client.connect()                                                                                                                            
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 319, in connect                                                         
    self.loop.run_until_complete(super().connect(login))                                                                                        
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                             
    return future.result()                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 178, in connect                                                         
    (self.transport, self.protocol) = await self.loop.create_connection(lambda: MFCProtocol(self.loop, self), '{}.myfreecams.com'.format(selecte
d_server), 8100)                                                                                                                                
  File "/usr/lib/python3.6/asyncio/base_events.py", line 733, in create_connection                                                              
    infos = f1.result()                                                                                                                         
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run                                                                       
    result = self.fn(*self.args, **self.kwargs)                                                                                                 
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo                                                                                 
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                     
socket.gaierror: [Errno -3] Temporary failure in name resolution                                                                                
root@ubuntu:~#                                                                                                                                  
 u  16.04 0:-*                                                                                  3! 1d7h 0.29 3.4GHz 2.0G38% 2017-11-16 06:41:09
