### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by reyaz006** [beaston02/MFCRecorder#38]
At some point, the script stops checking for active models. I'm not sure at which point exactly, but seems to happen once in 2-3 days.

Also, there was a situation when several models were being recorded, and one were displaying "preview unavailable". The script didn't record anything for her but I could see in her chat room that the stream was active. I had to restart the script to fix this.

Python 3.6, Windows.

**Comment by evilcorp9** [comment]
I'm having the same problem, I've been trying to log the error and this is what i've got:
Script was started on 2017-12-22 at 14:05:02
Everything worked great, cams were being recorded, until following event....
On 2017-12-23 at 05:50:44, after following exception, models stopped being recorded and I've got this error:

> 
> [2017-12-23 05:50:43] Connecting to MyFreeCams chat server xchatXX...
> 	[2017-12-23 05:50:44] Login handshake completed. Logged in as 'GuestXXXXX' with sessionId XXXXXXXXX
> 	[2017-12-23 05:50:44] Unexpected exception: <class 'urllib.error.HTTPError'>
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 60, in data_received
> 	    self.client.handle_packet_received(Packet(*unpacked_data[1:-1], smessage))
> 	  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 90, in handle_packet_received
> 	    self._process_packet(packet)
> 	  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 144, in _process_packet
> 	    self._handle_extdata(packet.smessage)
> 	  File "/usr/local/lib/python3.6/dist-packages/mfcauto/client.py", line 225, in _handle_extdata
> 	    with urllib.request.urlopen(url) as req:
> 	  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
> 	    return opener.open(url, data, timeout)
> 	  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
> 	    response = meth(req, response)
> 	  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
> 	    'http', request, response, code, msg, hdrs)
> 	  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
> 	    return self._call_chain(*args)
> 	  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
> 	    result = func(*args)
> 	  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
> 	    raise HTTPError(req.full_url, code, msg, hdrs, fp)
> 	urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by gabotronix** [comment]
I have the same problem. I'm on CentOS 7, Python 3.6. Although I don't have logs to show. At first, I thought it was a settings issue - time interval between checking who's online. The default value was 20 secs., so I changed it to 60 from the Web UI.

I always check the captures folder whenever I log into my server. I think today was my 4th or 5th straight day of the script running without issues. When I logged in today, I was surprised that my captures folder was empty again.

I checked the script and it was running. There is even 1 model online that it should be recording, but my captures folder was still empty. The logs showed these every 60 seconds:

> [2017-12-25 12:33:32,306] Login handshake completed. Logged in as 'Guestxxxxx' with sessionId xxxxxxxxx
655 models online
recording model_name: xxxxxxxx (68 viewers) [{'sweet', 'Classy', 'Xxxxxx', 'xxxx', 'xxxx', 'xxxx', 'xxxx', 'xxxxx', 'xxxx', 'xxxx', 'dancer', 'xxxx', 'xxx', 'xxx', 'mixed', 'xxx'}]
finished run

The Web UI did not seem to be updated when I checked. It was showing 4 models being recorded. Apparently, the script should only be recording 1 model at that time as shown in the script log. However, nothing was written to disk.

The only way to fix it was to press CTRL+C twice and then run the script again.

**Comment by David-Eilers** [comment]
i dont know why those exceptions occured but just to be sure you could check if your on the latest version of MFCRecorder and all MFCRecorder dependencies are updated.

in the case of @reyaz006 and @evilcorp9 , it could be MFC behaving funky and returning 404's for livestream snapshots thus tripping MFCRecorder and throwing exceptions.

Maybe this helps you to troubleshoot.

**Comment by gabotronix** [comment]
It happened again recently, but I captured some errors this time.

> File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 320, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='www.myfreecams.com', port=80): Read timed out. (read timeout=None)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "mfcrecorder.py", line 30, in <module>
    for uid, model in classes.models.get_online_models().items():
  File "/home/mfcrecorder/MFCRecorder/classes/models.py", line 10, in get_online_models
    server_config = requests.get(SERVER_CONFIG_URL).json()
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.myfreecams.com', port=80): Read timed out. (read timeout=None)
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by David-Eilers** [comment]
@sKanoodle should have a look at this since he wrote most of the logic for this new version.

But as far as i can see after some googling is that `requests.exceptions.ReadTimeout: HTTPConnectionPool(host='www.myfreecams.com', port=80): Read timed out. (read timeout=None)` signifies that the url (in this case mfc) did not send any info in the amount of time it had allocated for the request and thus triggering an exception.

I assume what happened next is other threads failing because of the exception stated above but i cannot say this with any certainty

This is the url i refered to: [Python.Requests ReadTimeout](http://docs.python-requests.org/en/master/_modules/requests/exceptions/#ReadTimeout)

**Comment by gabotronix** [comment]
It happened again and I have new errors.

> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4c3c83fbe0>: Failed to establish a new connection: [Errno 110] Connection timed out

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.myfreecams.com', port=80): Max retries exceeded with url: /_js/serverconfig.js (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c3c83fbe0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

> During  handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "mfcrecorder.py", line 30, in <module>
    for uid, model in classes.models.get_online_models().items():
  File "/home/mfcrecorder/MFCRecorder/classes/models.py", line 10, in get_online_models
    server_config = requests.get(SERVER_CONFIG_URL).json()
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.myfreecams.com', port=80): Max retries exceeded with url: /_js/serverconfig.js (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c3c83fbe0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by David-Eilers** [comment]
Based on those new exceptions the requests library MFCRecorder uses seems to have trouble retrieving the js file from mfc that lists all the chat and video servers .
`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.myfreecams.com', port=80): Max retries exceeded with url: /_js/serverconfig.js`
Because this file can't be retrieved `models.py` isn't able to retrieve all online models from mfc and throws an exception, this is the second portion of the exceptions posted above.

There are two things that most likely have happend:
1. It could be that due to a slow internet connection (or temporarily unstable connection) the http request could not be processed in the allotted time.
2. (This is the most likely cause in my eyes) Due to a high demand of traffic on mfc, the website isn't able to serve you the file in time thus resulting in a timeout of somesort.

Looking at the exceptions above i don't think there is a lot that could be done by MFCRecorder to prevent these exceptions. perhaps the js file could be cached but other then that i see no other solutions

**Comment by sKanoodle** [comment]
I really don't like the current way of getting the online models. mfcauto does seem to stop getting updates on online models some time after starting MFCRecorder. Also, it is written in async and I dont really have a clue yet about async in python. Escpecially on how to set timeouts and stop the async processes.
MFC does seem to have some kind of json api, that would be the perfect way to get information about online models. However, it is not at all documented, I only found out about it myself after snooping around in the js on the main MFC site. So far, I only found some kind of trending model data in the API. There is currently no sign of online streams data.

**Comment by gabotronix** [comment]
I am not sure if it's related to Internet connection since the script is installed on a server from Hetzner (somewhere in Europe). It also has capturebate-node and streamlink that capture streams from Bloomberg and one other news site a few times a day. Both don't have issues. It's only MFCRecorder that's frequently stopping.

**Comment by David-Eilers** [comment]
Well then it seems to be that mfc is just slow at certain times during the day and that we probably have to deal with that from now on.

**Comment by sKanoodle** [comment]
@gabotronix I just pushed an update to the feature/online-models branch. I stopped creating a new mfcauto client every time the script fetched the online models. Could you tell me if it runs better for you now?

**Comment by gabotronix** [comment]
@sKanoodle, @David-Eilers:
Thank you. Can you please confirm if what I did was correct?

I am not familiar with updating scripts. I just did a _git pull_ from my existing MFCRecorder folder. If I am correct, then the script is now running and I will report the results in the coming days. I check the server at least once a day.

> user@xx MFCRecorder]**$ git pull origin master**
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 20 (delta 7), reused 5 (delta 5), pack-reused 12
Unpacking objects: 100% (20/20), done.
From `https://github.com/beaston02/MFCRecorder`
> `*` branch            master     -> FETCH_HEAD
Updating `7d7c1bd..562e88d`
Fast-forward
 webapp/assets/style.scss         | 138 ++++++-------------------------------------------------
 webapp/templates/config.html     | 103 ++++++++++++++++----------------------------
 webapp/templates/layout.html     |  59 ++++++++++++++++++-------
 webapp/templates/login.html      |  22 ++++++++++++++------
 webapp/templates/start_page.html |  67 +++++++++++++++++++++-------------------------
 webapp/templates/wanted.html     | 102 ++++++++++++++++---------------------------------
 webapp/views.py                  |  10 ++++-----
 7 files changed, 236 insertions(+), 265 deletions(-)

> [user@xx MFCRecorder]**$ python3.6 mfcrecorder.py** 
another run 2018-02-03 08:30:28.244753
 `*` Running on `https://0.0.0.0:8778/` (Press CTRL+C to quit)
[2018-02-03 08:30:28,925] Connecting to MyFreeCams chat server xchat79...
[2018-02-03 08:30:29,370] Login handshake completed. Logged in as 'Guest82002' with sessionId 497165379
1110 models online
started recording xxxxxx
recording xxxxxx: 16906238 (153 viewers) [{'sexy', '1234', '5678'}]
...
finished run

**Comment by David-Eilers** [comment]
Yes this is the correct way to update the **master** branch. but if you want to retrieve the branch @sKanoodle talked about (feature/online-models) then you need to checkout that branch from github, [this](https://stackoverflow.com/questions/1783405/how-do-i-check-out-a-remote-git-branch) article talks about doing that.

It is also a good thing to run python `pip` using the command `pip install --upgrade -r requirements.txt` in the root of the repository to updated any requirements or install any added requirements

**Comment by gabotronix** [comment]
@David-Eilers, @sKanoodle:
Thanks, but I'm getting commit errors and I don't know why I'm being asked for a Github account to supposedly commit changes. I was able to switch to the feature/online-models branch, but I don't think I was able to pull the files based on the timestamp of mfcrecorder.py.

Anyway, I just created a new folder on the server then downloaded the feature/online-models zip from my browser. Next, I uploaded the zip file to the server, unzipped it, copied my config.conf and wanted.json files from the old folder to the new one. Finally, I ran the script from the new folder using `python3.6 mfcrecorder.py`.

Now I'm seeing a new Web UI and it seems that the log entries are less cluttered. I'll let you know in the following days if I see errors.

**Comment by David-Eilers** [comment]
You were probably getting commit errors because you modified the conf and wanted files and because of that git wants to first commit these changes before changing over to a new branch and that requires a github account.

The second way is probably the best way to do it in this case. the script should now be running properly and i hope all errors have been resolved.

**Comment by gabotronix** [comment]
@David-Eilers, @sKanoodle:

Unfortunately, I still got the errors as frequently as the script in the master repo. In fact, the script stopped 3-4 times since I first ran it a few hours ago. Please check the logs below. It's not included in the log, but I saw the js max connection retries error which may have started the whole thing.

> Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2018-02-05 06:31:25,430] Connecting to MyFreeCams chat server xchat119...
[2018-02-05 06:31:26,008] Login handshake completed. Logged in as 'Guest70751' with sessionId 517877260
Fatal read error on socket transport
protocol: <mfcauto.client.MFCProtocol object at 0x7f0af9dab908>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2018-02-05 07:29:11,158] Connecting to MyFreeCams chat server xchat79...
[2018-02-05 07:29:11,755] Login handshake completed. Logged in as 'Guest84189' with sessionId 518200067
Model_X's session has ended
Fatal read error on socket transport
protocol: <mfcauto.client.MFCProtocol object at 0x7f0af9e94e48>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2018-02-05 08:32:50,166] Connecting to MyFreeCams chat server xchat106...
[2018-02-05 08:32:50,660] Login handshake completed. Logged in as 'Guest80704' with sessionId 518596581
Fatal read error on socket transport
protocol: <mfcauto.client.MFCProtocol object at 0x7f0af80d1c18>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
Disconnected from MyFreeCams.  Reconnecting in 30 seconds...
[2018-02-05 09:38:30,006] Connecting to MyFreeCams chat server xchat120...
[2018-02-05 09:38:30,355] Login handshake completed. Logged in as 'Guest61757' with sessionId 519036165
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by David-Eilers** [comment]
At this point i have no clue as to why this keeps happening.
when i run MFCRecorder i leave it running for a while and i have not had any of your errors.
this is strange.

**Comment by gabotronix** [comment]
Thanks for letting me know. I'll try to run the script on a US-West BuyVM VPS.

**Comment by sKanoodle** [comment]
@gabotronix I put a try block around the server conf json thingy and allowed it to retry 10 times in case of an error (new commit to feature/online-models, you should be able to just git pull). This should hopefully fix your problems with this error. In case the error actually comes from mfcauto, there is not much I can do here, since that is developed by somebody else.

**Comment by David-Eilers** [comment]
@gabotronix i have it installed on: windows 10 python 3.6.2 and im in europe

**Comment by gabotronix** [comment]
@David-Eilers,
Okay thanks. It's also the same on the US-West VPS, but without the Python errors. Then it just terminated itself. I installed the master repo (on CentOS 7). I'll try the feature/online-models repo next.

> [2018-02-06 08:16:05,564] Login handshake completed. Logged in as 'Guest55705' with sessionId 524423943
fetching online model list timed out
finished run
another run 2018-02-06 08:17:05.325952
[2018-02-06 08:17:05,520] Connecting to MyFreeCams chat server xchat79...
[2018-02-06 08:17:05,672] Login handshake completed. Logged in as 'Guest36639' with sessionId 524432946
fetching online model list timed out
finished run
...
[2018-02-06 08:21:06,200] Login handshake completed. Logged in as 'Guest48682' with sessionId 524359986
Killed

**Comment by gabotronix** [comment]
Just an update on @sKanoodle's feature/online-models branch from the US-West VPS:

10 hours running so far, without errors/stoppage. I'm only tracking 1 model, so the script has been running mostly without captures.

> another run 2018-02-06 22:30:08.095617
mfcauto loaded: True
url loaded
2248 models online
finished run
another run 2018-02-06 22:30:28.079824
mfcauto loaded: True
url loaded
2243 models online
finished run
another run 2018-02-06 22:30:48.046420
mfcauto loaded: True
url loaded
2236 models online
finished run

**Comment by gabotronix** [comment]
Update on the feature/online-models branch from the US-West VPS:

Unfortunately, I'm back to the original issue of this thread. The script runs without errors but isn't really writing anything to disk. I have to CTRL+C and the re-run the script to get it working again.

> another run 2018-02-08 02:19:34.359956
mfcauto loaded: True
url loaded
2771 models online
recording Model_X: 12345678 (83 viewers) [{'friendly'}]
finished run

I'll try a Debian-based distro next time to see if it makes any difference.

**Comment by gabotronix** [comment]
An update on my installation on CentOS 7 x64 after 2 months:
Unfortunately, I didn't have the time nor the motivation to test the script any further. I simply went on and checked the server 2-4 times a day. The problem was not really solved.

I am now back to using sstativa's [mfc-node](https://github.com/sstativa/mfc-node), but he recently made an update that allowed the use of [hlsdl](https://github.com/samsamsam-iptvplayer/hlsdl) instead of rtmpdump. I've had no issues for the past 24 hours. I hope this continues.

I was using mfc-node rtmpdump before I came accross MFCRecorder. mfc-node rtmpdump captures became choppy after a while, that's why I had to look for another script. My captures are doing good thus far with mfc-node hlsdl.
