### ISSUE TITLE
Syntax error while launching the program 

### ISSUE THREAD

**Issue by fuomag9** [beaston02/MFCRecorder#40]
Traceback (most recent call last):
  File "mfcrecorder.py", line 7, in <module>
    import classes
  File "/root/MFCRecorder/classes/__init__.py", line 1, in <module>
    import classes.config
  File "/root/MFCRecorder/classes/config.py", line 8, in <module>
    import classes.helpers as helpers
  File "/root/MFCRecorder/classes/helpers.py", line 65
    return _get_img_from_url(URL_TEMPLATE.format(camserver - 500, uid + 100_000_000))
                                                                                  ^
SyntaxError: invalid syntax

**Comment by sKanoodle** [comment]
@fuomag9 do you use python 3.6?

**Comment by fuomag9** [comment]
3.5.2

**Comment by sKanoodle** [comment]
You will need python 3.6 to run this script.
