### ISSUE TITLE
Post Processing Problem

### ISSUE THREAD

**Issue by newtonslaw** [beaston02/MFCRecorder#45]
I am having an issue running post processing, and wondered if anyone had any ideas.  Immediately after the session has ended I get the following error, and no post processing steps are completed:

```
<model> session has ended
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/<user>/MFCRecorder/classes/postprocessing.py", line 22, in run
    subprocess.call(item)
  File "/usr/local/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not int
```
Running my post processing script manually it works OK, and I can also run it using test_postProcessing OK too, so I think my script is OK.

Any ideas?

**Comment by sKanoodle** [comment]
@newtonslaw what does your post_processing_command in the config look like?
