### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by MrOctober77** [beaston02/MFCRecorder#53]
Got the Chaturbate recorder working, now trying MFC

Tried using pthon3.6 and python3 to stat it
With Python3.6 I get:

Traceback (most recent call last):
  File "mfcrecorder.py", line 7, in <module>
    import classes
  File "/home/don/MFCRecorder/classes/__init__.py", line 1, in <module>
    import classes.config
  File "/home/don/MFCRecorder/classes/config.py", line 8, in <module>
    import classes.helpers as helpers
  File "/home/don/MFCRecorder/classes/helpers.py", line 9, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

With python3 I get:

Traceback (most recent call last):
  File "mfcrecorder.py", line 6, in <module>
    import mfcauto
ImportError: No module named 'mfcauto'

I installed numby and mfcauto is installed 

python3.6 -m pip install --upgrade git+https://github.com/ZombieAlex/mfcauto.py@master
Collecting git+https://github.com/ZombieAlex/mfcauto.py@master
  Cloning https://github.com/ZombieAlex/mfcauto.py (to master) to /tmp/pip-1n6wwbic-build
Installing collected packages: mfcauto
  Running setup.py install for mfcauto ... done
Successfully installed mfcauto-1.1.0

**Comment by polymath614** [comment]
you need to install numpy it does not come as part of of the python3

**Comment by sKanoodle** [comment]
removed the unused reference to numpy in https://github.com/beaston02/MFCRecorder/commit/4d623861aed533f430598e495da55ca8b1ae84e6

**Comment by MrOctober77** [comment]
Now when I run python3 mfcrecorder.py or python3 add.py I get:

Traceback (most recent call last):
  File "mfcrecorder.py", line 7, in <module>
    import classes
  File "/home/don/MFCRecorder/classes/__init__.py", line 1, in <module>
    import classes.config
  File "/home/don/MFCRecorder/classes/config.py", line 8, in <module>
    import classes.helpers as helpers
  File "/home/don/MFCRecorder/classes/helpers.py", line 64
    return _get_img_from_url(URL_TEMPLATE.format(camserver - 500, uid + 100_000_000))

**Comment by sKanoodle** [comment]
are you using python 3.6? the underscore syntax is only available in 3.6

**Comment by MrOctober77** [comment]
Yes I am using 3.6. If if try to run python3.6 mfcrecorder.py i get this:

Traceback (most recent call last):
  File "mfcrecorder.py", line 10, in <module>
    config = classes.config.Config(os.path.join(sys.path[0], 'config.conf'))
  File "/home/don/MFCRecorder/classes/config.py", line 79, in __init__
    self.refresh()
  File "/home/don/MFCRecorder/classes/config.py", line 98, in refresh
    self._filter = Filter(self._parser, self.settings)
  File "/home/don/MFCRecorder/classes/config.py", line 60, in __init__
    self.wanted = Wanted(settings)
  File "/home/don/MFCRecorder/classes/config.py", line 192, in __init__
    self._load()
  File "/home/don/MFCRecorder/classes/config.py", line 197, in _load
    self.dict = {int(uid): data for uid, data in json.load(file).items()}
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 9 (char 25)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "mfcrecorder.py", line 10, in <module>
    config = classes.config.Config(os.path.join(sys.path[0], 'config.conf'))
  File "/home/don/MFCRecorder/classes/config.py", line 79, in __init__
    self.refresh()
  File "/home/don/MFCRecorder/classes/config.py", line 98, in refresh
    self._filter = Filter(self._parser, self.settings)
  File "/home/don/MFCRecorder/classes/config.py", line 60, in __init__
    self.wanted = Wanted(settings)
  File "/home/don/MFCRecorder/classes/config.py", line 192, in __init__
    self._load()
  File "/home/don/MFCRecorder/classes/config.py", line 197, in _load
    self.dict = {int(uid): data for uid, data in json.load(file).items()}
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 9 (char 25
